stages:
    - build

build:
    stage: build
    image: golang:1.9.2
    cache:
        paths:
            - /apt-cache
            - /go/src/github.com
            - /go/src/golang.org
            - /go/src/google.golang.org
            - /go/src/gopkg.in
    
    
    before_script:
        - mkdir -p /go/src/gitlab.com/cardosomarcos /go/src/_/builds
        - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/cardosomarcos/dynamofilter
        - ln -s /go/src/gitlab.com/cardosoamrcos /go/src/_/builds/cardosomarcos
        - make dep
    script:
        # Compile and name the binary as `hello`
        - go build -o hello
        # Execute the binary
        - ./hello
